package response;

public
enum ResponseType {
     ALIVE_CONNECTION
    ,ACCEPT_SIGN_IN
    ,ONLINE
    ,USER_TOKEN
    ,ERROR_SIGN_IN
    ,ERROR_SIGN_UP
    ,ACCEPT_SIGN_UP
    ,UPDATED_MESSAGING_ENVIRONMENTS
    ,UPDATED_MESSAGING_ENVIRONMENT
    ,UPDATED_MESSAGES
    ,UPDATED_USERS
    ,ACCEPT_NEW_MESSAGE
    ,ACCEPT_EDIT_MESSAGE
    ,ACCEPT_DELETE_MESSAGE
    ,ACCEPT_SEEN
    ,LOGGED_IN_USER_RELATIONSHIP
    ,USER_RELATIONSHIP
    ,ERROR_NO_SERVER
    ,APPLY_RELATIONSHIP
    ,APPLY_REQUEST
    ,UPDATED_FOLLOWERS
    ,UPDATED_FOLLOWINGS
    ,UPDATED_BLOCKERS
    ,UPDATED_BLOCKEDS
    ,UPDATED_REQUESTS
    ,UPDATED_REQUESTEDS
    ,UPDATED_SILENTEDS
    ,ADD_MEMBER
    ,MODIFY_GROUP_INFO
    ,LEAVE_GROUP
    ,NEW_GROUP
    ,IS_USED_EMAIL
    ,IS_USED_USERNAME
    ,IS_CURRENT_PASSWORD
    ,CHANGE_USER_SETTING
    ,DEACTIVATE_ACCOUNT
    ,DELETE_ACCOUNT
    ,NEW_POST
    ,UPDATED_POSTS
    ,LIKE_POST
    ,USER_FOLLOWERS
    ,USER_FOLLOWINGS
    ,UPDATE_USER
    ,BLOCK_USER
    ,MUTE_USER
    ,PRIVATE_CHAT
    ,SEARCH_USER
    ,CATEGORIES
    ,CATEGORY
    ,CATEGORY_USERS
    ,NEW_CATEGORY
    ,DELETE_CATEGORY
    ,MODIFY_CATEGORY_USERS
    ,MODIFY_CATEGORY_INFO
    , UPDATED_NOTIFICATIONS
    ,SEEN_NOTIFICATION
    ,UPDATED_POST_LIKERS
    ,NEW_SCHEDULED_MESSAGE


}
